plugins {
    id 'org.jreleaser' version '1.21.0'
}

allprojects {
    apply from: rootDir.getAbsolutePath() +  '/gradle/java_base.gradle'
    apply from: rootDir.getAbsolutePath() +  '/gradle/maven_push.gradle'

    dependencies {
        api 'cn.featherfly.common:common-core:1.16.0'
        api 'org.slf4j:slf4j-api:1.7.30'
        
        testImplementation 'org.testng:testng:6.14.3'
        testImplementation 'org.slf4j:slf4j-log4j12:1.7.30'
    }
}
  
dependencies {  
    
}